name: Word Count
author: Virtuosi Media
category: Forms
tags: [text, word-count, character-count]
docs: http://www.virtuosimedia.com/dev/javascript/mootools-plugins/word-count/api-documentation
demo: http://www.virtuosimedia.com/dev/javascript/mootools-plugins/word-count/demos
current: 1.0